### ISSUE TITLE
XML files are not generated, can only be viewed through settings

### ISSUE THREAD

**Issue by lcaaroe** [Geta/SEO.Sitemaps#81] opened 2018-08-02 11:40 UTC
I've set up sitemap generation like this:
![image](https://user-images.githubusercontent.com/7383455/43581416-25c11264-9659-11e8-953b-c21c58d55b2d.png)

I get a success message when running the job:
![image](https://user-images.githubusercontent.com/7383455/43581455-4ea9cb94-9659-11e8-9d3b-3a1ff5968634.png)

But the file does not actually exist. I get a 404 if I try to access the url from the above image (/sitemap.xml), and the file does not physically exist in the website folder.

I can view the sitemap via settings, i.e. via /Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx.

SEO.Sitemaps version: 2.0.8
Episerver version: 11.9.2

Thanks in advance.

**Comment by SeleVlad** [comment] 2019-10-03 07:55
Hi,

I've had the same issue but it was happening because I was using an ActioFilter with was added as a global filter and was messing with the rendering.

**Comment by patkleef** [comment] 2019-10-04 08:24
@lcaaroe we configured these routes in the package. Could be the order of routes or an ActionFilter like @SeleVlad mentioned. The XML's are not physically stored in the website folder.

```
RouteTable.Routes.MapRoute("Sitemap index", "sitemapindex.xml", new { controller = "GetaSitemapIndex", action = "Index" });
            RouteTable.Routes.MapRoute("Sitemap without path", "sitemap.xml", new { controller = "GetaSitemap", action = "Index" });
            RouteTable.Routes.MapRoute("Sitemap with path", "{path}sitemap.xml", new { controller = "GetaSitemap", action = "Index" });
            RouteTable.Routes.MapRoute("Sitemap with language", "{language}/sitemap.xml", new { controller = "GetaSitemap", action = "Index" });
            RouteTable.Routes.MapRoute("Sitemap with language and path", "{language}/{path}sitemap.xml", new { controller = "GetaSitemap", action = "Index" });
```

**Comment by patkleef** [comment] 2019-10-24 23:08
Closing this issue, because I can't reproduce.

**Closed by patkleef** 2019-10-24 23:08 UTC
