### ISSUE TITLE
Sitemap Property not showing correct Enabled-value

### ISSUE THREAD

**Issue by tuube** [Geta/SEO.Sitemaps#97] opened 2019-08-20 07:56 UTC
We have added the Sitemap-property to our pages. The "Enabled" value shows always as true after publish. The value is changed in the databse, it just doesn't show it on the edit page.

**Comment by patkleef** [comment] 2019-08-21 13:36
@tuube do you use  the dynamic property or this one: 
https://github.com/Geta/SEO.Sitemaps#adding-sitemap-properties-to-all-content-pages

**Comment by tuube** [comment] 2019-08-22 07:44
We are using the NOT-dynamic property that you linked.

**Comment by patkleef** [comment] 2019-08-29 13:20
@tuube I'm not able to reproduce. Which version of the package have you installed? I tried with version 3.02.

**Comment by tuube** [comment] 2019-08-30 08:16
We are using version 2.0.13. I'll try if the newer version works better.

**Comment by patkleef** [comment] 2019-10-04 08:54
@tuube did you find the time to test with a newer version?

**Comment by tuube** [comment] 2019-10-07 05:22
Yes, I finally did, and it works with version 3.1.0. Thanks for your help @patkleef !

**Comment by patkleef** [comment] 2019-10-07 06:08
No problem, closing issue.

**Closed by patkleef** 2019-10-07 06:08 UTC
Labels: bug
