### ISSUE TITLE
BadImageFormatException: Cannot load a reference assembly for execution.

### ISSUE THREAD

**Issue by anton-dealmeida** [Geta/SEO.Sitemaps#105] opened 2019-09-03 08:47 UTC
EPiServer Version: 11.11.1.0
GetaTags Version: 4.0.3.0 

We are trying to install and add this SEO.Sitemaps NuGet package next to our nearly complete CMS solution. Currently we are experiencing an issue where our solutions break, initially it worked on the person who originally added the packages but broke everywhere else including on release to integration in DXC.

Right now, it gives us a System.Runtime exception error with BadImageFormatException. It has something to do with the assembly binding done in the web.config.

Any ideas?
![image](https://user-images.githubusercontent.com/18613828/64158058-24a82300-ce38-11e9-8993-4173536b4718.png)

![image](https://user-images.githubusercontent.com/18613828/64158039-1bb75180-ce38-11e9-964e-26bbbb487162.png)

**Comment by patkleef** [comment] 2019-09-03 09:08
@anton-dealmeida I assume that when you uninstall the package everything works again?

**Comment by anton-dealmeida** [comment] 2019-09-03 09:21
Yeah

**Comment by patkleef** [comment] 2019-09-03 10:54
I'll try to reproduce with a clean Alloy demo site.

**Comment by patkleef** [comment] 2019-09-03 11:24
@anton-dealmeida can't reproduce. Can you post here the changes after installing the sitemaps package?

**Comment by anton-dealmeida** [comment] 2019-09-04 05:00
Sorry that I took long to get back. I'll try and do that, if all else fails I'll share a link to you to connect to my visual studio instance and to go through it with me. I might just be crazy..

**Comment by patkleef** [comment] 2020-03-26 09:38
Closing this issue. Please open a new issue when it happens again.

**Closed by patkleef** 2020-03-26 09:38 UTC
